# 该文件问项目的第三方库管理文件，类似 package.json

# 键值对，表示app的名字为flutter_app
name: flutter_app
description: A new Flutter application.
# 环境，flutter的sdk版本在此之间
# environment:
  # sdk: ">=2.0.0-dev.68.0 <3.0.0"

# 依赖库
dependencies:
  http: ^0.12.0+4
  # flutter:
  #   sdk: flutter
  # cupertino_icons: ^0.1.2
  # event_bus: ^1.0.1
  # shared_preferences: "^0.4.3"
  # flutter_refresh: ^0.0.1

#测试环境的依赖库
# dev_dependencies:
#   # flutter_test:
#   #   sdk: flutter

# flutter:
#   #使用Material图标
#   uses-material-design: true
#   #assets文件
#   assets:
#     - images/head.png
#     - images/1.gif
#   #字体样式
#   fonts:
#      #family与fonts是一个整体，列表的一项
#      - family: Schyler
#        fonts:
#          - asset: fonts/Schyler-Regular.ttf
#          - asset: fonts/Schyler-Italic.ttf
#            style: italic
#      - family: Trajan Pro
#        fonts:
#          - asset: fonts/TrajanPro.ttf
#          - asset: fonts/TrajanPro_Bold.ttf
#            weight: 700